language: r
sudo: false
cache: false

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

script:
  - Rscript -e "rmarkdown::render('notebook/rladies19-complete.Rmd')"
